// front-svelte/src/component/Create.svelte
<script>
  import 'bootstrap/dist/css/bootstrap.min.css';
  import Swal from 'sweetalert2';
  import axios from 'axios';
  import * as yup from 'yup';
    import {Form, Message} from 'svelte-yup';
    let schema = yup.object().shape({
        name: yup.string().required().max(30).label("Name"),
        job_role: yup.string().required().max(50).label("Job Role"),
        salary: yup.string().required().label("Salary"),
        birth: yup.string().required().label("Birth"),
        employee_registration: yup.string().required().label("Employee Registration")
    });
    let fields = { name: ""};
    let submitted = false;
    let isValid;
    function formSubmit(){
        submitted = true;
        isValid = schema.isValidSync(fields);
        if(isValid){
          axios.post('http://localhost:3001/api/employees', {
            name: fields.name,
            job_role: fields.job_role,
            salary: fields.salary,
            birth: fields.birth,
            employee_registration: fields.employee_registration,
          }).then(result => {
        Swal.fire({
          title: 'Employee created successfully!',
          icon: 'success',
          showConfirmButton: true,
          allowOutsideClick: false,
          allowEnterKey: true,
          allowEscapeKey: false,
        }).then((data) => {
          window.location.href = '/'
        });
      });
        }
    }
</script>


<section>
  <div class="container">
    <div class="card">
<div class="card-header">
<h3>Add Employee</h3>
</div>
<div class="card-body">
<!-- svelte-ignore component-name-lowercase -->
<Form {schema} {fields} submitHandler={formSubmit} {submitted}>
<div class="form-group">
<label for="name">Name</label>
<input type="text" class="form-control" name="name" id="name" bind:value={fields.name} placeholder="Name"/>
<Message name="name" />
</div>
<div class="form-group">
<label for="job_role">Job Role</label>
<input type="text" class="form-control" name="job_role" bind:value={fields.job_role} placeholder="Job Role" id="job_role"  />
<Message name="job_role"  />                  

</div>
<div class="form-group">
<label for="salary">Salary</label>
<input type="number" class="form-control"  name="salary" bind:value={fields.salary} placeholder="Salary" id="salary" />
<Message name="salary"  />       
</div>
<div class="form-group">
<label for="birth">Birth</label>
<input type="date" class="form-control" name="birth" bind:value={fields.birth} placeholder="Birth" id="birth" />
<Message name="birth"  />               
</div>
<div class="form-group">
<label for="employee_registration">Employee Registration</label>
<input type="number" class="form-control" name="employee_registration" bind:value={fields.employee_registration} placeholder="Employee Registratio" id="employee_registration" />
<Message name="employee_registration"  />                
</div>
<button type="submit" class="btn btn-primary">Salvar <i class="fa fa-save"></i></button>
</Form>
</div>
</div>
</div>
</section>


<style>
</style>

// front-react/src/components/create.js
import React from "react";
import 'bootstrap/dist/css/bootstrap.css';
import axios from "axios";
import { useForm } from  'react-hook-form';
import { ErrorMessage } from '@hookform/error-message';
import Swal from 'sweetalert2';
import 'font-awesome/css/font-awesome.min.css';



const Create = (props) => {
  const { register, handleSubmit, formState: { errors } } = useForm();
  const onSubmit = data => {
      axios.post('http://localhost:3001/api/employees', data).then(result => {
        Swal.fire({
          title: 'Employee created successfully!',
          icon: 'success',
          showConfirmButton: true,
          allowOutsideClick: false,
          allowEnterKey: true,
          allowEscapeKey: false,
        }).then((data) => {
          window.location.href = '/list'
        });
  });
 
};



      
     
    return (
       
        <div className="container">
        <br />
        <br />
        <hr />
        <div className="card">
  <div className="card-header">
    <h3>Add Employee</h3>
  </div>
  <div className="card-body">
<form onSubmit={handleSubmit(onSubmit)}>
<div className="form-group">
<label htmlFor="name">Name</label>
<input type="text" className="form-control" name="name" {...register("name", { required: "This field is required." })} />
                            <ErrorMessage
        errors={errors}
        name="name"
        render={({ message }) => <p className="alert alert-danger">{message}</p>}
      />
</div>
<div className="form-group">
<label htmlFor="job_role">Job Role</label>
<input type="text" className="form-control" name="job_role" {...register('job_role',{ required: "This field is required." })} />
                            <ErrorMessage
        errors={errors}
        name="job_role"
        render={({ message }) => <p className="alert alert-danger">{message}</p>}
      />

</div>
<div className="form-group">
<label htmlFor="salary">Salary</label>
<input type="number" className="form-control"  name="salary" {...register('salary',{required: "This field is required.",pattern: {
              value: /^[0-9]/,
              message:
                "Sorry this CodeSandbox can only handle names with characters"
            }})} />
                            <ErrorMessage
        errors={errors}
        name="salary"
        render={({ message }) => <p className="alert alert-danger">{message}</p>}
      />
</div>
<div className="form-group">
<label htmlFor="birth">Birth</label>
<input type="date" className="form-control" name="birth" {...register('birth',{required: "This field is required."})} />
                            <ErrorMessage
        errors={errors}
        name="birth"
        render={({ message }) => <p className="alert alert-danger">{message}</p>}
      />
</div>
<div className="form-group">
<label htmlFor="employee_registration">Employee Registration</label>
<input type="number" className="form-control" name="employee_registration" {...register('employee_registration',{required: "This field is required."})} />
                            <ErrorMessage
        errors={errors}
        name="employee_registration"
        render={({ message }) => <p className="alert alert-danger">{message}</p>}
      />
</div>
<button type="submit" className="btn btn-primary">Salvar <i className="fa fa-save"></i></button>
 </form>
  </div>
  </div>
</div>
    )   
}
 
export default Create;
